version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.754

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - clojure-v1-dependencies-{{ checksum "deps.edn" }}
            - clojure-v1-dependencies-

      - run: bin/ci
      - store_test_results:
          path: test-results/kaocha
      - store_artifacts:
          path: test-results/coverage
          destination: coverage

      - save_cache:
          paths:
            - ~/.m2
          key: clojure-v1-dependencies-{{ checksum "deps.edn" }}
